// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.pagosonline.logica;

import com.pagosonline.logica.Cliente;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect ClienteDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ClienteDataOnDemand: @Component;
    
    private Random ClienteDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Cliente> ClienteDataOnDemand.data;
    
    public Cliente ClienteDataOnDemand.getNewTransientCliente(int index) {
        com.pagosonline.logica.Cliente obj = new com.pagosonline.logica.Cliente();
        obj.setNombre("nombre_" + index);
        obj.setDireccion("direccion_" + index);
        obj.setTelefono("telefono_" + index);
        return obj;
    }
    
    public Cliente ClienteDataOnDemand.getSpecificCliente(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Cliente obj = data.get(index);
        return Cliente.findCliente(obj.getId());
    }
    
    public Cliente ClienteDataOnDemand.getRandomCliente() {
        init();
        Cliente obj = data.get(rnd.nextInt(data.size()));
        return Cliente.findCliente(obj.getId());
    }
    
    public boolean ClienteDataOnDemand.modifyCliente(Cliente obj) {
        return false;
    }
    
    public void ClienteDataOnDemand.init() {
        data = com.pagosonline.logica.Cliente.findClienteEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Cliente' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<com.pagosonline.logica.Cliente>();
        for (int i = 0; i < 10; i++) {
            com.pagosonline.logica.Cliente obj = getNewTransientCliente(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
