// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.pagosonline.logica;

import com.pagosonline.logica.CuentaDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CuentaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CuentaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CuentaIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: CuentaIntegrationTest: @Transactional;
    
    @Autowired
    private CuentaDataOnDemand CuentaIntegrationTest.dod;
    
    @Test
    public void CuentaIntegrationTest.testCountCuentas() {
        org.junit.Assert.assertNotNull("Data on demand for 'Cuenta' failed to initialize correctly", dod.getRandomCuenta());
        long count = com.pagosonline.logica.Cuenta.countCuentas();
        org.junit.Assert.assertTrue("Counter for 'Cuenta' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CuentaIntegrationTest.testFindCuenta() {
        com.pagosonline.logica.Cuenta obj = dod.getRandomCuenta();
        org.junit.Assert.assertNotNull("Data on demand for 'Cuenta' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Cuenta' failed to provide an identifier", id);
        obj = com.pagosonline.logica.Cuenta.findCuenta(id);
        org.junit.Assert.assertNotNull("Find method for 'Cuenta' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Cuenta' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CuentaIntegrationTest.testFindAllCuentas() {
        org.junit.Assert.assertNotNull("Data on demand for 'Cuenta' failed to initialize correctly", dod.getRandomCuenta());
        long count = com.pagosonline.logica.Cuenta.countCuentas();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Cuenta', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.pagosonline.logica.Cuenta> result = com.pagosonline.logica.Cuenta.findAllCuentas();
        org.junit.Assert.assertNotNull("Find all method for 'Cuenta' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Cuenta' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CuentaIntegrationTest.testFindCuentaEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Cuenta' failed to initialize correctly", dod.getRandomCuenta());
        long count = com.pagosonline.logica.Cuenta.countCuentas();
        if (count > 20) count = 20;
        java.util.List<com.pagosonline.logica.Cuenta> result = com.pagosonline.logica.Cuenta.findCuentaEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Cuenta' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Cuenta' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CuentaIntegrationTest.testFlush() {
        com.pagosonline.logica.Cuenta obj = dod.getRandomCuenta();
        org.junit.Assert.assertNotNull("Data on demand for 'Cuenta' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Cuenta' failed to provide an identifier", id);
        obj = com.pagosonline.logica.Cuenta.findCuenta(id);
        org.junit.Assert.assertNotNull("Find method for 'Cuenta' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCuenta(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Cuenta' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CuentaIntegrationTest.testMerge() {
        com.pagosonline.logica.Cuenta obj = dod.getRandomCuenta();
        org.junit.Assert.assertNotNull("Data on demand for 'Cuenta' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Cuenta' failed to provide an identifier", id);
        obj = com.pagosonline.logica.Cuenta.findCuenta(id);
        boolean modified =  dod.modifyCuenta(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.pagosonline.logica.Cuenta merged = (com.pagosonline.logica.Cuenta) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Cuenta' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CuentaIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Cuenta' failed to initialize correctly", dod.getRandomCuenta());
        com.pagosonline.logica.Cuenta obj = dod.getNewTransientCuenta(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Cuenta' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Cuenta' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Cuenta' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CuentaIntegrationTest.testRemove() {
        com.pagosonline.logica.Cuenta obj = dod.getRandomCuenta();
        org.junit.Assert.assertNotNull("Data on demand for 'Cuenta' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Cuenta' failed to provide an identifier", id);
        obj = com.pagosonline.logica.Cuenta.findCuenta(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Cuenta' with identifier '" + id + "'", com.pagosonline.logica.Cuenta.findCuenta(id));
    }
    
}
